### PR TITLE
Chapter 5 images

### PR DESCRIPTION
**Pull request by ghost**
- Line width consistent
- Fill area now renders under curves instead of on top in many cases
- Axis renders on top when graphs lines would render on them
- Lines are consistently smooth
- Arrow styling consistent 
- Colors are consistent
- All commented lines removed

Some things I observed doing this chapter
- Cannot use addplot+ with images with area fill since they need to render after the fill meaning firstcurvestyle should be used instead.
- Arrows used sparingly and mostly on open lines with no fill and not used in exercises.
- Not sure what to do with fillarea color styling as theres no newer macros for them. Have to keep the old ones that look like: "[{\coloronefill},fill={\coloronefill}]".
- "smooth" and "samples=X" are very useful for smoothing out graphs. I only use smooth on plots with "coordinates" as "samples=X" will not work since the sample points are given. For samples I use this on every other curve with a varying amount between 40 and 70 usually.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
Thanks for this, Lyle.
As far as filling goes: take a look at index.ptx over on APEXCalculusPTX. Alex gave me some fill commands to add/try. See if that works for you.

**Comment by sean-fitzpatrick** [comment]
Here is the revised first curve style.. You can do the same for second and third if needed:

\pgfplotsset{firstcurvestyle/.style={color=firstcolor,mark=none,thick,{Kite}-{Kite},solid,fill=firstcolor!50,fill=none}}

Then just put 'fill' in the argument of the \addplot+

**Comment by lpsnelgrove** [comment]
> Thanks for this, Lyle.
> As far as filling goes: take a look at index.ptx over on APEXCalculusPTX. Alex gave me some fill commands to add/try. See if that works for you.

It does fill but the curve commands also inherit bordering in some way so the fill area has a border around it and the fill is much more opaque if that was intended.

For some reason color needs to be set to {\coloronefill} or {\colortwofill} to keep the border away. Other color commands fuch as firstcolor!50 or something similar add a border.

**Comment by ghost** [comment]
> Here is the revised first curve style.. You can do the same for second and third if needed:
> 
> \pgfplotsset{firstcurvestyle/.style={color=firstcolor,mark=none,thick,{Kite}-{Kite},solid,fill=firstcolor!50,fill=none}}
> 
> Then just put 'fill' in the argument of the \addplot+

I removed my old comment because I saw a graph where this worked but that was a lucky coincidence. It definitely cleans up the code but the color=firstcolor!50 causes the fill area to get borders. If we use the old color command {\coloronefill} it makes it go away and I am not sure why still.

**Comment by sean-fitzpatrick** [comment]
Ok, we can ask Alex to take a look.
The !50 sets the opacity to 50%.

**Comment by ghost** [comment]
Should that be correct? The old opacity was 15 with white mixed in. It is very heavy looking at 50.

**Comment by sean-fitzpatrick** [comment]
We can redefine it by changing the global setting.
But maybe that will be bad for other images.
Let me ask Alex to take a look.

PS: you can check against the original PDF as a point of comparison, if you aren't already.
My version is here: [http://www.cs.uleth.ca/~fitzpat/Textbooks/Math1565_ebook.pdf](http://www.cs.uleth.ca/~fitzpat/Textbooks/Math1565_ebook.pdf)

**Comment by sean-fitzpatrick** [comment]
Can you post some screenshots to give us an idea of what's going wrong?
Are you mostly dealing with the shaded rectangles in the Riemann sums section?

**Comment by sean-fitzpatrick** [comment]
Since colorone fill is defined with blue!15!white can we make that change in the firstcurvestyle definition and see what happens? Do we ever need a fill with secondcurvestyle?

**Comment by ghost** [comment]
> Can you post some screenshots to give us an idea of what's going wrong?
> Are you mostly dealing with the shaded rectangles in the Riemann sums section?

Yes those ones are causing an issue for sure but other shapes were getting them as well. I'll upload an image here in a minute.

> Since colorone fill is defined with blue!15!white can we make that change in the firstcurvestyle definition and see what happens? Do we ever need a fill with secondcurvestyle?

I only have 1 image that uses the secondcurvestyle fill but it doesn't utilize the fill option yet. Also all editing the command does it make the fill lighter but the border is still there. It appears when we specifically use {\coloronefill} does the border go away.

**Comment by ghost** [comment]
This was taken from my chapter 6 branch since That was the one I was working on. Same issue however.

image


Is what is generated by this code:
```
\begin{tikzpicture}

\begin{axis}[
axis on top,
xtick={1,5,10},
ymin=-.1,ymax=.5,
xmin=-1,xmax=11
]

%\addplot [{\coloronefill},fill={\coloronefill},domain=1:10.5,samples=100] {ln(x)/x^2} -- (axis cs:10.5,0) -- (axis cs:0,0) -- cycle;
\addplot+ [-,domain=1:10.5,samples=100,fill] {ln(x)/x^2} -- (axis cs:10.5,0) -- (axis cs:1,0) -- cycle;

\draw (axis cs:5,.3) node {\scriptsize $\ds f(x)=\frac{\ln(x) }{x^2}$};

\end{axis}

\end{tikzpicture}
```

This is what is generated when I add the new firstcurvestyle command in. The fill is really dark and there is a dark blue border around all of it. This is not how they appear in the book.

EDIT: Code had a bug with the cycle part of the command so I updated it and uploaded a new image.

**Comment by sean-fitzpatrick** [comment]
I see only one image.
Is this using \coloronefill or firstcurvestyle?

**Comment by ghost** [comment]
I only posted one image. I put the edit in just in case you saw it before I finished the edit. It will use firstcurvestyle from the newer index you sent me. The first line is commented out since that was the old fill plot.

**Comment by sean-fitzpatrick** [comment]
Added some adjustments to the style commands.
Use these along with the feedback you got from Alex and you should be good.

Main notes:

Use separate lines to draw the fill, then the border:
`\addplot [firstcurvestyle,areastyle, domain=a:b] {curve} \closedcycle`
`\addplot [firstcurvestyle, domain=a:b] {curve}`

Fill colour will correspond to firstcurvestyle, secondcurvestyle, etc.

**Comment by ghost** [comment]
Ok that is sort of what I had in mind as a fix. Would be cool to use a single command then we could use addplot+ but this is will and it is very close to what I was going to do anyways. I will touch up chapter 5 here tonight and do 6 tomorrow.

EDIT: did some research from Alex's post instead since he brings up some good points. Will continue chapter 5 Sunday and hopefully have it up to par with your above code (which does work really well) and with some considerations from Alex's post.

**Comment by ghost** [comment]
- Images now use functions instead of coordinates. This greatly reduces code clutter and increases readability/maintainability. Also, not we can use samples=X to fine tune the curve resolution instead of 'smooth' which greatly increased file size. Using a smaller sample number that still gives a smooth curve helps reduce image size. Image size was a consideration from the reply Alex made and even though it is different than his proposal, I feel overall we will save space compared to the current book version.
- A couple weird images at the bottom of numberical_integration.ptx still use older code but they are very ad hoc so I didn't worry too much about them.
- I did make a small modification to the second and third curve style code as a couple of graphs did use the second one differently. As we go through later chapters I will make sure that images still behave correctly.

**Comment by sean-fitzpatrick** [comment]
OK, approving these changes.
As per the comments from Alex, use caution when increasing the number of sample points, since it pushes up the file size. (In some projects, the book will come with images in PDF, SVG, EPS, etc. So even small increases in file size can multiply.)

Often you want more samples near points with a lot of curvature or steep tangents, which is why you're seeing images where the points are assigned manually. But as Alex suggests, you can mitigate this by choosing clever coordinate systems.

And avoid "smooth". It can add weird defects on curves, especially if a curve is supposed to have some points where it *isn't* smooth. (At a cusp, it might draw a little loop in an attempt to 'smooth out' the curve.)

**Comment by ghost** [comment]
I only use smooth reserve for old style curves that use coordinates because the image isn't easily converted or even possible and they have to use it to make them smooth. I definitely do not add it to any new curves. Size really isn't an issue since we are only dealing with a couple MB of data at most here or there for the entire 13 chapters and while it is good to be space conscious, it really makes a very little difference to even the slowest or limited of internet connections. I am however keeping it as small as I can and I would say that most images are shrinking (>90%) anyways just from updating them so its a pretty easy request to accommodate.

**Pull request merged**
