### PR TITLE
Chapter 12 images

### PR DESCRIPTION
**Pull request by ghost**
- Completed latex images
- Was going to to asymptote images in chapter 7 but I am having issues getting them to compile with MBX. It just hangs during the conversion from .asy to .svg. Will have to continue to investigate and I wonder if it requires any changes to the current asymptote code.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
The problem is that the Asymptote code is all for 3D PRC images. SVG is a 2D format.
So I'm not sure there's an easy conversion.

**Comment by sean-fitzpatrick** [comment]
Possibly relevant:
[https://sourceforge.net/p/asymptote/discussion/409349/thread/27b15a6b/?limit=25#9225](https://sourceforge.net/p/asymptote/discussion/409349/thread/27b15a6b/?limit=25#9225)

**Comment by sean-fitzpatrick** [comment]
OK. If you look in the figures folder (see either APEXCalculusV5 or APEXCalculusPTX repos) you'll notice that for each fig_foo.asy file there is also a fig_foo3D.asy file.
I think what's happened is that the 3D files were imported, but those don't convert to SVG.
I'll open a thread on the APEX conversion Google group.

**Comment by sean-fitzpatrick** [comment]
Please try changing `asy` to `asy -noprc` in mathbook/user/mbx.cfg and see if that helps.
Possibly useful discovery: many (if not all) of the Asymptote images also have TikZ counterparts.
So there's a fallback option.

**Comment by ghost** [comment]
I have not had much luck with asymptote images at all. Looks like the config file for mbx doesn't accept parameters at all so I ran all the commands manually with the asy executable. I have tried the one built in with miktex with and without the -noprc flag, I have also tried the official release of aymptote on both windows and Linux and all the images do is hang with no feedback.

I read the post so it looks like we could use the tikz code but it would be cool to use as much asymptote as possible if we get it working.

**Comment by sean-fitzpatrick** [comment]
Ok, thanks for the report. 
It might be good to move this to pretext-dev (or maybe support) with a MWE that demonstrates the issue 

I wonder if you could work around with a bash script. For example, since I can't install pdf2svg on CentOS, there's a file with that name that's actually a small bash script containing `pdftocairo -svg #1 #2`.

**Comment by ghost** [comment]
In that post you linked I thought it was funny that in 2018 WebGL would only be a few months away and its getting closer to 2020 now. Looks like whenever that gets released will solve a fair bit of our issues. 

I think it might be possible at this time to convert only the 2D images and if the tikz code exists we could swap in the tikz code for 3D images.

**Comment by ghost** [comment]
> I wonder if you could work around with a bash script. For example, since I can't install pdf2svg on CentOS, there's a file with that name that's actually a small bash script containing `pdftocairo -svg #1 #2`.

That might work. Just have a small function that does it. Let me see if I can get something here.

Give this a try:
```
pdf2svg() {
  pdftocairo -svg $1 $2
}
```
Depending on how its called if it is in a script it could be more complicated but if you are running from a terminal it should be fine. Just add it to your .bashrc and source it:
```
source .bashrc
```

**Comment by sean-fitzpatrick** [comment]
Yeah, I have this working already for mbx on the CentOS machine at work.
I'm suggesting something similar to get the -noprc option into the Asymptote call

**Comment by ghost** [comment]
Ohh. I don't think that is possible. However I did modify my mbx script to include the flag for the asymptote call. On line 109 which looks like this:
```
asy_cmd = [asy_executable, '-offscreen', '-batchMask', '-outformat', outformat, asydiagram]
```
we can add the flag like so:
```
asy_cmd = [asy_executable,'-noprc', '-offscreen', '-batchMask', '-outformat', outformat, asydiagram]
```

However this didn't change anything for me with regards to not hanging forever during the conversion. Also I don't know if it matters but I cannot covert to a pdf either for any images.

**Comment by sean-fitzpatrick** [comment]
Hmm. We might have to ask for help with debugging.
First step might be to make a .tex file with one or two Asymptote images, and confirm that it compiles. (It should.)

**Comment by sean-fitzpatrick** [comment]
OK, I have mbx working for asymptote in a minimal example.
Please test:

1. Comment all lines starting with usepackage and texpreamble in asymptote code.
(You probably do a global replace if you're careful to avoid \usepackage lines in index.ptx, or do it one section at a time.)

2. Either add -noprc to the mbx script as discussed above, or add the line `settings.prc = false;` as the **very first** line in each asymptote code block.

3. Run mbx with `mbx -v -c asy -f pdf -d <output directory> <filename>`

This is working for me on Ubuntu 18.04 (It was failing miserably on CentOS.)

**Comment by ghost** [comment]
So I did some troubleshooting and I think I found the hidden issue since I still couldn't compile. When using -vv with mbx I was able to see the /tmp directories where the code gets stored before it gets compiled. These .asy files I could not compile because they have the texpreamble added to it. I removed these 2 lines and was able to compile but still couldn't run get through mbx.
```
\DeclareMathOperator{\sech}{sech}
\DeclareMathOperator{\csch}{csch}
```
I looked at the log file and noticed that we use an old package that was removed with an update but was able to manually reinstall it in the miktex console. For reference it was l3backend.

After adding that package and with those above lines removed I can compile with the command on ubuntu perfectly but I have to put the settings.prc = false; into the file as running it in the mbx script doesn't do anything for me. Not sure why those lines are causing issues either. The log file isn't very helpful for that one.

Also, I can sometimes compile files on windows. The console will lock up like before but I will get a pdf in the temp directory for it. Seems to be that I cannot compile any of the 3D images that use graph3 in any capacity however. 

Looks like I will have do all my asymptote testing on my laptop but I guess I should ask if we want to put the settings.prc = false in all the 3D files? (I don't think the 2d need it and they are all in chapter 14 so far). If so I can do a PR with every chapter from 7 onwards that adds that line and removed the others. Then just test them and mark any that will not compile.

**Comment by sean-fitzpatrick** [comment]
Those two preamble commands are defining hyperbolic secant and cosecant functions (which are not predefined for some reason).

Those don't show up in ones I tried so presumably those commands are used in a label?
You could replace (for example) `\sech` with `\operatorname{sech}` and then you wouldn't need those commands.

My testing on Ubuntu shows that adding -noprc to the mbx script is doing what it should. Not sure why it won't work for you.

You could hard code it in each asymptote code block of you want. It might interfere with WebGL later but it would be easy to comment out.

**Comment by sean-fitzpatrick** [comment]
I have mbx working on Asymptote for Chapters 7 and 10.
Basically, you just have to run with -vv and then go into the temp folder if it fails.
Whatever one it fails on, all the .tex auxiliary files will still be there. Find the .log file for the image that failed and go to the bottom to see what the TeX error is -- usually an undefined control sequence.
Not sure why `\DeclareMathOperator` fails.
But replace those lines with `\newcommand{\sech}{\operatorname{sech}}` and similar for csch.

In the section on lines, there is a command \vv that is undefined. There is an equivalent line that is commented out that doesn't use the macro.
Probably better is to change which line is commented, but a quick fix is to define
`\newcommand{vv}[1]{\overrightarrow{#1}}`.

Side note: in sec_space_coord you missed a subsection that picked up the xml:id of `fig_coordplanes`, which is used in a figure later on, so there are multiply-defined references.

**Comment by ghost** [comment]
I also noticed that when testing the new trig commands that in chapter 6 there were 2 more commands not working. The absolute value command and the ampersand symbol ```\abs and \amp```. What we should do is do a new PR that updates all of these commands including the above fixes and get that onto master for testing as it is getting out of the scope of this branch and there might be more of these we haven't noticed yet.

As it is all the image branches are complete and getting them in and doing some overall testing would be more useful at this point. If any issues come up we can document them and fix them in a new PR.

**Comment by ghost** [comment]
Fixed ```fig_coordplanes``` issue. The subsection apparently had the same ID as a figure but the xref within that subsection references the figure so I just removed the ID off the subsection as it was no longer needed.

**Comment by sean-fitzpatrick** [comment]
In Asymptote comments you might have to use `&amp;` if \amp doesn't work.

The absolute value command is defined in the preamble, which is loaded. So if that's not working you might need to add usepackage(amsmath) to the Asymptote code.

**Comment by sean-fitzpatrick** [comment]
OK, I tried adding `usepackage("amsmath")` to all `<asymptote>` blocks, and I can run mbx with zero errors now. (It spotted a couple of multiply-defined xml:ids which I'll hope are fixed in these PRs.)
Couldn't figure out the right regex on Atom, but with Sublime I did
`<asymptote>\n\s*?\n(\s*?)`
for find (which takes me up to the beginning of `import graph3` to get the indendation right), and replace with
`<asymptote>\n\1usepackage("amsmath");\n\n\1`

That was enough to resolve any remaining errors.

**Comment by ghost** [comment]
Ok, so should that be added to every instance of an asymptote image in all chapters?

**Comment by sean-fitzpatrick** [comment]
Yes. It's not necessary for some images, but it won't cause harm if it isn't used.
This is easier than figuring out where it's needed and adding it on a case by case basis.

**Comment by ghost** [comment]
Alright, I will add it to the rest of these image chapters then we can do more testing on a global basis. I will create a PR after with some notes on the last things we need to do overall including testing and the latex preamble.

**Review by sean-fitzpatrick — APPROVED** [review]

**Pull request merged**
