### PR TITLE
Chapters 4 and 5 updates

### PR DESCRIPTION
**Pull request by ghost**
Ran fix-deprecations on chapters 4 and 5. No odd errors but the new code Sean added that was missing required correcting some img tags with the new image tag with tikz code.

Did add some missing xml:id references that were getting referenced too in some figures that had it stripped.

### CODE REVIEW

**Review by sean-fitzpatrick — CHANGES_REQUESTED** [review]
There are still a few instances of \<description/\> and \<cell/\> that should be paired tags.
sec_FTC has & gt ; in pg-code. This isn't a problem as far a processing goes; it just makes the code a little harder to read.
A lot of WW problems use \ds (displaystyle) which generally isn't recommended, but maybe in webwork it's ok. We should ask Alex.
For TikZ code: you generally want to keep lines specifying xticks and xtick lables (same for y).
Instances of \addplot [thick, \colorone], etc. can become \addplot+

**Comment by ghost** [comment]
Interesting, I completely missed going through the TFC section. Will update that file appropriately as well as fixing the \<cell\> tags. Attempting to test images before I merge...

**Comment by ghost** [comment]
@sean-fitzpatrick Should we be doing any image work as we go along with these chapters? I'm still debating if we should do those in a second pass.

**Comment by sean-fitzpatrick** [comment]
I think for now, if the image compiles, that's good enough.
Make some obvious changes, like getting rid of width, and replacing the old \colorone, etc with the updated versions (firstcurvestyle, etc).
Add a TODO tag so we know to come back to it.

**Comment by ghost** [comment]
To clarify, does that mean all instances of \<image\> in this repo should have their width param stripped if it exists?

**Review by sean-fitzpatrick — APPROVED** [review]

**Comment by sean-fitzpatrick** [comment]
Ah, sorry. To be clear:
If width is specified in a figure, image or sidebyside tag, leave it there.
Any width specification *within TikZ code* should be removed, as part of the process of cleaning up that code.

**Pull request merged**
