### PR TITLE
Chapter 6 validation

### PR DESCRIPTION
**Pull request by ghost**
Creating this early so I can ask a question.

I will go back and update 4 and 5 but maybe a having a checklist of things to fix would be good.

As far as I know this needs to be done for each section generally:
- run validation-fix over the file
- check that \> is only in pg-code
- check that \lt and \gt are in \<m\> (and \<me\>) tags only
- check that \&gt; is only in image code
- check that \&lt; is used everywhere (unless still wrapped in CDATA, \&amp; too)
- CDATA should be gone for most cases if \< and \> are used correctly
- adjust width for any webwork images which could be naked or in a \<sidebyside\> (which should be standard?)
- modify \<description/\> and  \<cell/\> to be an empty open and close tag
- add a \<description\> tag for images that lack one
- \<caption /\> is fine since we will likely not add to it unlike a \<description/\> or  \<cell/\>
- check if any figures moved around in a \<sidebyside\> that require a valid xml:id as a xref somewhere still might need it
- check if any captions get commented out since those need to be included still
- remove \<sidebyside\> wrapper if it contains only a single element
- fix anything fixable that the validation script spits out

If I am missing anything let me know.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
All of the above sounds right. Also watch for \<cell\>\</cell\> being turned into \<cell/\>.
Irrelevant for processing, but better for readability in the code.
(The same reason for preferring > in pg-code over & g t ;.)
My comment on the other pull request (requesting changes) has some suggestions for editing the tikz code as well. There are a couple of styling issues I wasn't sure about that I've asked Alex about on the APEX forum.

**Comment by ghost** [comment]
Looks like some words are missing. Anything between an \< and \> symbol pair doesn't show up on here but I can edit your comment to see what it was. Looks like all you need to do is escape them and they will show up. Must be a markdown thing.

does sound kinda funny though. Should we also do the same for caption?

**Comment by ghost** [comment]
Some oddities:

In sec_hyperbolic:
- There is a weird \<list\> that looks weird and doesn't validate nicely. Has a title that causes some trouble. Could redo the whole thing with a table perhaps?
- Strange incomplete \<insight\>  I am not sure what to do with.

In sec_sec_improper_integration:
-  There is an ugly aside that won't validate but I think it should be just inline text since it pops in and out of existence only when entering the example but its outside the example space so it feels weird to use.
- Something called an \<nbsp\> that does its thing but I don't know exactly what it is nor what could replace it easily.

**Comment by sean-fitzpatrick** [comment]
I'll look over these, but probably not until next week. nbsp is a non breaking space. It prevents a line break from happening at that spot. A list with a title is supposed to be allowed now.

**Comment by sean-fitzpatrick** [comment]
Forgot to add: self-closing caption tags are ok. I think we can use this convention:
Self closing means we don't ever intend to put something there.
Paired tags with nothing between means we'll eventually add the missing content.
The exception to this is cell. David advised against using self closing for an empty cell. I'm fine with that but don't feel strongly either way.

**Comment by ghost** [comment]
Will adjust some images before this gets merged. Will do the same with chapter 7 and the 4 + 5 branch.

**Comment by sean-fitzpatrick** [comment]
The lists in the hyperbolic section are fine. Recent schema change actually reverts something back here so that this was once deprecated, but no more. Those violations should go away with an update to pretext.
The insight only gets flagged as incomplete because it contains another violation.

**Comment by sean-fitzpatrick** [comment]
The problem with the lists is that the schema doesn't specify that a list is allowed inside an "insight" (or any "remark-like" environment). But a table isn't allowed either!
Those non-breaking spaces are in a title, within math mode. That whole title is problematic. Someone will have to look at it later.

**Comment by sean-fitzpatrick** [comment]
The problem with the aside was that it was inside a paragraph. Moving it out fixed that violation.
Having it pop in and out of existence is a little weird, but I think that's expected. It refers to something in the example, so it wouldn't make sense to have it visible if the example isn't.

**Review by sean-fitzpatrick — APPROVED** [review]

**Comment by sean-fitzpatrick** [comment]
A request on pretext-dev and minutes later, Rob has the schema updated to allow a list inside an insight. The only remaining violation is the nbsp.
But there are some character encoding issues with webwork problems in the l'Hospital's rule section.

**Comment by sean-fitzpatrick** [comment]
Merging this now. We can deal with the hat-o situation later.

**Pull request merged**
