### PR TITLE
Chapter 10 validation

### PR DESCRIPTION
**Pull request by ghost**
- in sec_space_coord.ptx There were some figures that consisted of a parent figure but it was 3 images one after the other separated by an ampersand. I just wrapped these images in figures and wrapped those in \<sidebyside\>. I think there were 2 or 3 of them.

Work in progress

### CODE REVIEW

**Comment by ghost** [comment]
Nothing too unusual in this chapter except maybe now well formatted sec_planes.ptx is. That file had:
- 0 violations
- perfect indentation (even on comments for images/figures which never happens)
- no \&gt; needed to stay in (a couple \&lts though)
- all figures and images were id'd the same and consistently with the example
- no \<sidebyside\>s, no \<tabular\>s, no problems
- proper use of \<introduction\>, \<exercisegroup\> and \<subsection\>
- no loose text

Who wrote that file? It is definitely the one to emulate and it is what I try to go for.

**Comment by sean-fitzpatrick** [comment]
I think some of those figures used to be arranged in a (LaTeX) table, which is why the ampersands are there. (You can confirm by viewing the original PDF.)

Didn't go through the whole sec_space_coord (that's a huge diff) but noticed a few places where you made small changes to the asymptote code (adjusting a coordinate, or a width, etc.)

We should maybe meet to go over these. I'd like to get a better grasp on the asymptote images, including understanding those changes.

**Comment by ghost** [comment]
Weird, I have no idea why those were changed. I guess I was doing a find and replace and it accidentally grabbed some of it. So far the only changes to the asymptote code I have intentionally done are indent it correctly.

We definitely will need to figure out what to do with them since I haven't the slightest clue how to compile them or what the commented out chucks above them is for.

**Comment by sean-fitzpatrick** [comment]
I noticed this one:
```
 -      \includemedia[width=95pt,3Dmenu,activate=onclick,deactivate=onclick,
 +      \includemedia[width=100pt,3Dmenu,activate=onclick,deactivate=onclick,
      3Droll=0,
  -    3Dortho=0.004,
  +    3Dortho=0.0044,
```

A bit further down, some coordinates are changed.

**Comment by ghost** [comment]
@sean-fitzpatrick everything looks good here now. You will not see changes for space_coord as the one on here is the same updated one on master.

**Pull request merged**
