### PR TITLE
Chapter 6 images

### PR DESCRIPTION
**Pull request by ghost**
- Some of the images use coordinates to make simple graphs. I converted a handful for testing such as the one in sec_lhopitals_rule where it was x^x but it looked like:
`\addplot [{\colorone},thick,smooth] coordinates {(0.01,0.955)(0.02,0.9247)(0.03,0.9001)(0.04,0.8792)(0.05,0.8609)(0.06,0.8447)(0.07,0.8302)(0.08,0.817)(0.09,0.8052)(0.1,0.7943)(0.2,0.7248)(0.3,0.6968)(0.4,0.6931)(0.5,0.7071)(0.6,0.736)(0.7,0.7791)(0.8,0.8365)(0.9,0.9095)(1.,1.)(1.1,1.111)(1.2,1.245)(1.3,1.406)(1.4,1.602)(1.5,1.837)(1.6,2.121)(1.7,2.465)(1.8,2.881)(1.9,3.386)(2.,4.)};`
I just changed it to `\addplot+ [domain=0:2,samples=50] {x^x};` and it worked perfectly.
That incudes a bunch in sec_improper_integration since I couldn't resist - they look great too. It is no problem to do these even if it is a bit more advanced.
- Many images with fill will need to be updated more when borders stop being an issue.
- Also corrected an image where the function were mislabeled.

### CODE REVIEW

**Comment by ghost** [comment]
@sean-fitzpatrick Tagging since some discussion on this branch could be helpful before I continue too much further. Not sure if I want to jump into 7 since I will very likely have to go through 4-6 again to clean up fill stuff (4 maybe being in the other repo). 

Also I dug around in my email notifications so I should see these github messages instantly instead of hours later which is annoying for both of us.

**Comment by sean-fitzpatrick** [comment]
Great, thanks.
Yeah, these get pushed aside in my email too...
I'll be seeing Alex tomorrow in Banff. We'll go over this on the weekend and have some answers for you then.

**Comment by ghost** [comment]
Sounds good. I just want to make sure that the way I updated those images is good since they are an entire overhaul and we never really discussed doing it. In the meantime I will continue doing small changes but if these look good I will continue overhauling them if it fits.

**Comment by ghost** [comment]
When doing inverse functions, a quick trick is to give the original function but make it into a parameterized plot by wrapping the function with the line to invert on (namely x). Then, add "swapaxes" in the styling and you will get an inverse plot.

The code below gives hyperbolic cosine and its inverse without having to plot coordinates which brings space and code optimizations. 
```
\addplot+ [domain=0:3] {cosh(x)};
\addplot+ [domain=0:3,swapaxes] (cosh(x),x);
```
Some trouble occurs with hyperbolic inverse trig functions as pgfplots doesn't support these natively and the current solutions are a little code messy compared to hyperbolic tan, cosine and sine so I have left these as coordinates and updated what I could.

I also made some changes to certain curves that have really sharp bends that make it easier to generate smoother curves without consuming a ton of space through sample points. See the image discussion post: https://github.com/PCCMathSAC/apex-mbx/issues/120

**Comment by sean-fitzpatrick** [comment]
For inverse hyperbolic functions, there are formulas you can use. This is "Key Idea 6.6.13" -- see the old conversion here: [http://spot.pcc.edu/math/APEXCalculus/sec_hyperbolic.html](http://spot.pcc.edu/math/APEXCalculus/sec_hyperbolic.html)

**Review by sean-fitzpatrick — APPROVED** [review]
These all look good to me. I'm going to approve and merge. I'll try to get through Chapter 6 soon and do a build, and we'll see if any issues come up.

**Pull request merged**
