### PR TITLE
Chapter 14 everything

### PR DESCRIPTION
**Pull request by ghost**
- Completed moving over the images and fixed the validation for the first 2 files. However images will need to be tested still.
- Added child figure IDs and ensured all current parent figure references were still valid.
- In this section (as well as a bit of chapter 13 i think) Some of the styling of how text is formatted for referencing figures is weird. For instance, all references refer to the parent figure and use (a), (b), etc like
```
In <xref ref="fig_vectorfieldintro1">Figure</xref>(a),
```
Since we let captions letter themselves some of these look weird especially in the multipart example in sec_vector_fields which uses (c) and (d). These should be updated to be consistent with earlier chapters where every figure is directly referenced. Also within references such as
```
In <xref ref="fig_vectorfieldintro1">Figure</xref>
```
The word 'Figure' is not rendered but the actual xref element will add that word in so every instance of this could be removed in all chapters.

Just as one quick example, this line from above could be updated from
```
In <xref ref="fig_vectorfieldintro1">Figure</xref>(a),
```
to
```
In <xref ref="fig_vectorfieldintro1a"></xref>,
```
I have kept the new ids very close to the parent figure id so it is very simple to find the figure that these old letter references point to. Since they were not part of image code or validation I have not changed them as I feel a better time for them is when we are proof reading in the later stages after the code is moved to the PTX repo.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
Thanks Lyle. The original LaTeX had the (a), (b), etc. for captions.
The machine conversion left them in place. You're seeing them because nobody made it this far last time.
Please feel free to adjust references as you've described.

**Comment by ghost** [comment]
- Continued onto the next couple files
- Latex images are tested and working
- noticed some of the math equations are a bit weird when compiling some of the files (vector_fields is one). They appear to render the first command as text before the rest of the equation specifically
```
\divv and \curl
``` 
- Updated the format for xrefs to no longer use the parent figure but to use the new IDs on the child figures. Captions have all been fixed previously no xrefs have been changed in those chapters. See the above commit to see what it would look like.
- Will test and verify asymptote images in this PR for chapter 14 and will do the rest when they are merged.

**Comment by sean-fitzpatrick** [comment]
This chapter uses some new macros (e.g. `\curl`) that are not defined in the latex preamble in index.ptx.
You'll need to track those down in the original LaTeX and put them in. They'll be in either the preamble of the Calculus.tex master file or in a headers file that gets included.

**Comment by ghost** [comment]
Weird appendix thing at the end of the last section, stokes_divergence. It is past all of the exercises and I am not sure what to do with it. Looks somewhat unfinished.

Just need to test asymptote images still and finish the last part of the last file then all done.

**Comment by sean-fitzpatrick** [comment]
stokes_divergence is the last section in the book, so that's where the appendices ended up.
Probably this should be in its own file, and included at the bottom of index.ptx.

If you look in the original LaTeX, after the text sections, there's an appendix.
In the appendix is the answers to odd-numbered exercises, and the index.
(These are generated automatically by PreTeXt, so no need to pay special attention there.)
After the appendix was the material you're seeing, which was meant to be the content just inside the back cover. (If you look at any commercial calculus book, there's always a table of basic formulas at the very back.)

**Comment by ghost** [comment]
- Moved the index out but It should be wrapped as a chapter perhaps. Also it has lots of issues still as I think when it was ran through the script to convert it to pretext it broke a lot with it. I found the original version in a PDF from the Uleth repo but I was only able to do so much right now. Definitely need to have a discussion on it (images work however, except the first one).

**Comment by ghost** [comment]
All of those \DeclareMathOperator functions are still causing me to be unable to compile asymptote images. On the plus side I don't need to manually add -noprc to files anymore. Don't really know why I had to in the first place. I did change them to the other version you gave me which allow me to compile but I will have to test them in html to ensure they work.

**Comment by ghost** [comment]
- Was able to do a full compile and the images appear to be working.
- Fixed an issue with a latex command \surfaceS not being in the index.
- Fixed some formatting in the appendix but there are some issues there. It appears a tabular needs a p tag wrapper or it won't render. The table at the bottom is not scrolling within the assemblage.
- Various latex errors that I think all involve the \big command (especially with \abs). The common trigonometric identities part wont render either. Might have something to do with the sidebyside

**Comment by sean-fitzpatrick** [comment]
The appendix is definitely not done.
I tried to organize things using 'assemblage' but this isn't allowed within a sidebyside.

Got stuck on how to proceed but pushed the work in progress so I didn't lose changes and could work on it at home.

**Comment by ghost** [comment]
Ok should we move that into its own PR (perhaps in the PTX repo?) since it is the only thing really holding up this branch and it is not related to chapter 14? The latex issue is also a small problem but we could also handle that in the test-fix branch since that also has that issue.

**Comment by sean-fitzpatrick** [comment]
For now I think just comment out the appendix and leave it as a to do item.

**Pull request merged**
