### PR TITLE
Chapter 7 validation

### PR DESCRIPTION
**Pull request by ghost**
- Lots of webwork images within a \<sidebyside\> with only 1 element.
I removed the \<sidebyside\> since it was unnecesary but I got complains that images should not be in a \<statement\>. I do not recall if I have seen that specific image error before but I assume it will be supported.

- Quite a few exercises with only images in the problem statement. Complains that it wants a \<p\> tag with some text but I don't think that should be an issue.

- Looks like xml:ids aren't on some figures initially and when we run the fix-dep script it makes things a bit more confusing especially with a \<sidebyside\> involved. I have added ids that I believe are correct where the original source dropped them since there are dangling xrefs that would point to them. As well some of the images lose there \<figure\> wrapper which had its own xml:id that was sometimes referenced. I had rewrapped a lot of those images. This seems to only really be an issue in chapter 7 so far, it was really rare but simple in previous chapters.

- A weird figure that probably needs a rewrite in sec_arc_length.ptx. I have left a TODO for it.

- Separated some exercises into groups as there were \<p\> tags with some text in between chunks of exercises that appeared to act as a seperator. The first group tended to do this but stopped after it so I made it consistent between these "chunks". Made the \<p\> text the into to the new group.

### CODE REVIEW

**Comment by ghost** [comment]
Did a small experiment with the figure ids. Since we are pulling all the figures into the source we can rename them without losing reference to the old non-existent files. I noticed that in multifigure examples using (a), (b)... the figures ids are never referenced, instead the parent figure is referenced but with (a), (b)... tacked on manually. 

All I did was rename the figures so that the child ones are consistent. i.e. the first is the parent id with "_a" tacked on (or something very similar). Then when editing the source later these can be referenced quickly and easily.

I also do not delete the START, END comments that describe the original figure and image id so if an image needs to be referenced when combining the old and new source it can work as a reference.

I have added some ids to figures in other chapters but I have only done this in this chapter but I am curious to know if you like this concept and if we should continue with it.

**Comment by sean-fitzpatrick** [comment]
In the earlier chapters you'll find examples of sidebyside panels where the images are in figures as fig1a, fig1b, etc. So this is consistent with earlier practice. The manual (a), (b) references can then be removed.

**Comment by sean-fitzpatrick** [comment]
I'm going to merge this. Some suggestions, probably coming too late since you're well along with things.
- there's no harm in leaving the sidebyside wrapper in place for now. If it gets officially removed later, I bet the deprecation fix will deal with it.
- maybe not a bad idea to go through and manually inspect/clean up figures before running the utility, if you think it's messing things up a bit. But maybe just as easy to fix after the fact?

**Comment by ghost** [comment]
It was pretty rare to see a messed up figure so fixing them didn't lost much time.

**Comment by sean-fitzpatrick** [comment]
Ok. Speaking of messed up figures, are you getting a bounding box that's way too big when you run mbx on Windows?

**Pull request merged**
